apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: ccteam4acr.azurecr.io/delivery
          ports:
            - containerPort: 8086
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: EMBED_TOMCAT_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: spring-dev
                  key: JAVA_OPTS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-dev
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-dev
                  key: DB_PASS
