apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverymanagement
  labels:
    app: deliverymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverymanagement
  template:
    metadata:
      labels:
        app: deliverymanagement
    spec:
      containers:
        - name: deliverymanagement
          image: username/deliverymanagement:latest
          ports:
            - containerPort: 8080
 